### ISSUE TITLE
站台無法編輯

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ElvisChiang/welly#69]
```
如圖所示
原因不明的無法編輯站台
圖片中可以看出目前有四個儲存的站台
但是站台列表當中卻無列出任何東西，也無法選取

這個問題從OSX 10.8~10.9都一樣（我從10.8開始加入MAC家族的）

希望能解決這個BUG
謝謝
```

Original issue reported on code.google.com by `CHCOO...@gmail.com` on 6 Dec 2013 at 8:58

Attachments:
* [螢幕快照 2013-12-06 下午3.57.05.png](https://storage.googleapis.com/google-code-attachments/welly/issue-69/comment-0/螢幕快照 2013-12-06 下午3.57.05.png)

**Comment by ElvisChiang** [comment]
same as #73, close
